spring:
  application:
    name: youtube-stats-bot

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN:${secrets.TELEGRAM_BOT_TOKEN}}
  users:
    chatIds: ${TELEGRAM_BOT_CHAT_IDS:${vars.TELEGRAM_BOT_CHAT_IDS}}
