spring:
  application:
    name: youtube-stats-bot

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN:${secrets.TELEGRAM_BOT_TOKEN}}
  users:
    chatIds: ${TELEGRAM_BOT_CHAT_IDS:${vars.TELEGRAM_BOT_CHAT_IDS}}
google:
  youtube:
    api-key: ${GOOGLE_YOUTUBE_API_KEY:${secrets.GOOGLE_YOUTUBE_API_KEY}}
    secret:
      client_id: ${GOOGLE_YOUTUBE_CLIENT_ID:${secrets.GOOGLE_YOUTUBE_CLIENT_ID}}
      client_secret: ${GOOGLE_YOUTUBE_CLIENT_SECRET:${secrets.GOOGLE_YOUTUBE_CLIENT_SECRET}}
      refresh_token: ${GOOGLE_YOUTUBE_REFRESH_TOKEN:${secrets.GOOGLE_YOUTUBE_REFRESH_TOKEN}}
    url:
      redirect_url: "http://localhost:8080/oauth2/callback"
      gemini_url: "https://generativelanguage.googleapis.com/v1/models/gemini-1.5-flash-001:generateContent?key="
      token_url: "https://oauth2.googleapis.com/token"


