name: Build Check for Spring Boot Projects

on: [ pull_request ]

jobs:
  build:
    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_BOT_CHAT_IDS: ${{ secrets.TELEGRAM_BOT_CHAT_IDS }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 23
      - name: Gradle Build
        run: ./gradlew build
