name: Build Check for Spring Boot Projects

on: [ pull_request ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Gradle Build
        run: ./gradlew build --full-stacktrace
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build/
          if-no-files-found: error

  upload-lambda:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: build/
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1
      - name: Upload Lambda
        run: aws lambda update-function-code --function-name youtube-stats-bot --zip-file fileb://build/distributions/youtube-stats-bot-0.0.1.zip | jq 'del(.Environment)'
